<h1>BIO</h1>
<p>Since bursting onto the scene in 2011, Platinum selling recording artists Pentatonix have sold more than 2.8 million albums in the U.S. alone, won multiple Grammy Awards, sold out venues worldwide, have amassed over 1.4 billion views on their YouTube channel with over 10.1 million subscribers and appeared in the feature film Pitch Perfect 2.  Their latest release, Pentatonix debuted at #1 on the Billboard Top 200 and Current Albums Chart and is certified gold by the RIAA.  The first single, “Can’t Sleep Love” has over 18 million views on YouTube and their most recent holiday album That’s Christmas To Me, is certified double platinum by the RIAA featuring their recent 2016 Grammy winning track, “Dance of the Sugarplum Fairy.”<br>
 
All 7 of their releases have peaked within the Top 5 on Billboard’s Digital Albums Chart with 6 of those releases reaching the Top 10 or higher on the Billboard Top 200 Album Chart. The group received 2 gold certifications for their “Daft Punk” medley and cover of Imagine Dragons’ “Radioactive”. Their 2014 holiday album, That’s Christmas To Me has sold more than 1.7 million copies in the U. S. and was the 4th best-selling album of 2014. The group released their very first documentary (On My Way Home) which follows the quintet on their sold out 2015 North American Tour featuring behind-the-scenes footage, live performance and the making of their debut studio album, Pentatonix.  The group is set to embark on their 2016 World Tour starting in April.</p><br>
 
<h2>SCOTT HOYING</h2>
<p>Scott is a songwriter and pianist who has been performing since the age of 8.  Following his graduation from Martin High School in Arlington, TX, Scott enrolled at USC where he joined the SoCal VoCals, a popular and accomplished campus a cappella group.  Involved with a variety of musical projects, Scott has been a finalist on CBS’ Star Search and has performed the National Anthem and “God Bless America” at numerous professional and collegiate sporting events, including home games for the Texas Rangers, Dallas Cowboys and Dallas Mavericks.</p>

<h2>MITCH GRASSI</h2>
<p>Mitch is the youngest member of Pentatonix and a recent high school graduate (he was a high school senior when taping of The Sing-Off commenced).  In addition to immersing himself in music theater in Arlington, TX, Mitch’s music tastes skew heavily toward underground club and electronic music.  A veteran of many vocal and talent competitions, Mitch took first place at the Teen Talent Follies for his rendition of Scott Alan’s “Kiss the Air.”  Mitch is honing his skills in production and DJ-ing while excelling as a lead vocalist for Pentatonix. </p>

<h2>KIRSTIN MALDONADO</h2>
<p>Kirstin is a National Hispanic Scholar and was a sophomore Music Theater major at The University of Oklahoma before joining Pentatonix.  She developed her vocal and performance skills during her eight years as a touring member at Theatre Arlington where she’d learned to sing eight-part harmonies.  She began her classical training during high school and was a member of the Texas All State Choir for three years.  A four-year show choir member and dance captain, Kirstin held numerous roles in local stage productions, performing at shows around the Metroplex, including Casa Manana and Bass Hall. </p>

<h2>AVI KAPLAN</h2>
<p>Avi is a serious student of classical music who also plays guitar, composes and arranges music for both choral and a cappella.  A Visalia, CA native, Avi moved to Walnut, CA in 2007 to attend Mt. San Antonio College, known worldwide for their strong choral and a cappella tradition.  In 2008 he joined Fermata Nowhere, a high-energy male a cappella group that became the first community college a cappella entrants to win the prestigious ICCA.  Avi won the competition’s award for “Best Rhythm Section,” the first year that this award had ever included a vocal bass (the award was called “Best Vocal Percussionist” before Avi’s victory prompted the language change).  In his third year at Mt. San Antonio, Avi joined Sincopation, an award-winning jazz ensemble that won the Monterey Jazz Festival Competition in his first year.  He has performed at venues worldwide, including New York City’s Lincoln Center and Carnegie Hall.</p> 

<h2>KEVIN “K.O.” OLUSOLA</h2>
<p>Kevin grew up in the small town of Owensboro, Kentucky, the son of a Nigerian psychiatrist and a Grenadian nurse.  At an early age, Kevin began learning piano, cello and saxophone.  He performed at Carnegie Hall twice as soloist on the cello and saxophone and has appeared on NPR’s “From The Top."  After finishing high school at Phillips Academy Andover, Kevin enrolled in Yale University where he was pre-med and majored in East Asian Studies.  He spent 18 months in Beijing becoming fluent in Chinese as a part of his Yale fellowship.  While in college, Kevin began developing his “celloboxing” skills and in 2009, he won second place in the “Celebrate and Collaborate with Yo-Yo Ma” international competition.  Ma would call Kevin's celloboxing version of "Dona Nobis Pacem" both “inventive and unexpected.”  In 2011, Kevin’s “Julie-O” celloboxing YouTube video was featured by CBS, AOL, Huffington Post and Washington Post, among others.  Kevin was also named one of 100 “History Makers in the Making” by NBC’s TheGrio and was hand-chosen by Quincy Jones to represent him in concert at the 2012 Montreux Jazz Festival alongside Bobby McFerrin and Chick Corea. On March 10th 2015, Kevin released his first solo album, The Renegade EP. courtesy of RCA Records. The album debuted #1 on Billboard Traditional Classical and Classical Crossover charts, in addition to staying #1 on iTunes classical albums for weeks as it featured classically reimagined versions of popular songs like “All of Me,” “Stay With Me,” and “Heart Attack,” as well as Kevin’s original composition “Renegade.”</p>